import "./src/styles/landing.scss"
import "./src/styles/menu.scss"
import "./src/styles/about.scss"
import "./src/styles/process.scss"
import "./src/styles/portfolio.scss"
import "bootstrap/dist/css/bootstrap.min.css"
